# Generated by Django 6.0.4 on 2026-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the guest menu.', null=True, upload_to='menu_items/'),
        ),
    ]
