"""
Django settings for rms_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-71=ge^c*6u#pjfxt^nc3lg@cn0qf%jrphu*xtk5g)1!i8im7f8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'restaurant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rms_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# —— django-unfold: modern admin UI (https://unfoldadmin.com)
UNFOLD = {
    "SITE_TITLE": "RMS Admin",
    "SITE_HEADER": "Restaurant Management",
    "SITE_SUBHEADER": "Menu · orders · floor · inventory",
    "SITE_SYMBOL": "restaurant",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "rms_project.settings.environment_callback",
    "COLORS": {
        "base": {
            "50": "oklch(98% .005 145)",
            "100": "oklch(95% .01 145)",
            "200": "oklch(90% .015 145)",
            "300": "oklch(82% .02 150)",
            "400": "oklch(68% .025 155)",
            "500": "oklch(52% .03 155)",
            "600": "oklch(42% .028 155)",
            "700": "oklch(34% .025 155)",
            "800": "oklch(26% .02 155)",
            "900": "oklch(18% .018 155)",
            "950": "oklch(12% .015 155)",
        },
        "primary": {
            "50": "oklch(97% .02 95)",
            "100": "oklch(93% .04 90)",
            "200": "oklch(88% .07 88)",
            "300": "oklch(82% .1 86)",
            "400": "oklch(78% .12 84)",
            "500": "oklch(72% .14 82)",
            "600": "oklch(64% .13 80)",
            "700": "oklch(54% .11 78)",
            "800": "oklch(44% .09 76)",
            "900": "oklch(34% .07 74)",
            "950": "oklch(24% .05 72)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "navigation": [
            {
                "title": "Service",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Tables",
                        "icon": "table_restaurant",
                        "link": reverse_lazy("admin:restaurant_table_changelist"),
                    },
                    {
                        "title": "Reservations",
                        "icon": "event",
                        "link": reverse_lazy("admin:restaurant_reservation_changelist"),
                    },
                    {
                        "title": "Orders",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:restaurant_order_changelist"),
                    },
                ],
            },
            {
                "title": "Menu & stock",
                "collapsible": True,
                "items": [
                    {
                        "title": "Menu items",
                        "icon": "restaurant_menu",
                        "link": reverse_lazy("admin:restaurant_menuitem_changelist"),
                    },
                    {
                        "title": "Recipes",
                        "icon": "scale",
                        "link": reverse_lazy("admin:restaurant_menuitemrecipe_changelist"),
                    },
                    {
                        "title": "Inventory",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:restaurant_inventoryitem_changelist"),
                    },
                ],
            },
            {
                "title": "Access",
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    return ["Development", "success"]
